### ISSUE TITLE
Dead project? 

### ISSUE THREAD

**Issue by eonist** [adamburmister/gitprint.com#49]
Any alternatives out there? 

Such a nice concept!

**Comment by adamburmister** [comment]
Not a dead project, just a quiet one :)

I welcome any contributions (so i can publish it to gitprint.com), but I'm slow to develop on this at the moment.

**Comment by eonist** [comment]
2 years slow or is there work behind the scene?

**Comment by adamburmister** [comment]
There's desire behind the scenes :)

**Comment by eonist** [comment]
This kind of throwing a stone in a glasshouse, but it would be really helpfull to see a UML diagram of the structure of the project.

Im procastinating on this my self for my big open source project. But iIdid one for a smaller opensource project and its quite helpfull. 

https://github.com/eonist/SqliteEdit/wiki

And here is one that explains an algorithm:

https://github.com/eonist/GitSyncOSX/wiki/UML

**Comment by eonist** [comment]
Would you care to share these wants for the future then?

**Comment by eonist** [comment]
I really dont get why opensource projects dont focus more on explaining project structures if they want contributions.  im slinging stones in my own glasshouse now. :P

**Comment by eonist** [comment]
Anyways. Just driving by. Lovly project. The right dev could turn this to gold in a week.
