### ISSUE TITLE
Chrome extension link broken

### ISSUE THREAD

**Issue by spences10** [adamburmister/gitprint.com#58]
I get a 404 from the [https://gitprint.com/](https://gitprint.com/) web page when trying to get the Chrome add-in

This is the link it's pointing to:
[https://chrome.google.com/webstore/detail/print-github-markdown-git/fhnfikabkgjdcbgncedbgiapobklkahb](https://chrome.google.com/webstore/detail/print-github-markdown-git/fhnfikabkgjdcbgncedbgiapobklkahb)

**Comment by adamburmister** [comment]
Thanks for the report. 

It looks like Google has removed all trace of it. There is an alternative published ext now though at https://chrome.google.com/webstore/detail/gitprint/igmdhkjenljbkggljeobknjgehilnjmp from another author.

**Comment by spences10** [comment]
Works fine, thanks man! 👍 
Is there any way to change the syntax highlighting??
